### PR TITLE
2.0.1 - bump deps, add badges, rm unused parameters and variables

### PR DESCRIPTION
**Pull request by eagleeye**

### CODE REVIEW

**Comment by eagleeye** [comment]
@freeall, how about transfering this module to your personal account?

**Comment by freeall** [comment]
@eagleeye good idea, I'll do that now :)

**Comment by freeall** [comment]
Haha, I can't do that. Can you transfer it?

**Comment by freeall** [comment]
I meant, can you transfer it to me?

**Comment by eagleeye** [comment]
@freeall i can, but after approval from Visma. Or return it back to e-conomic if not

**Comment by eagleeye** [comment]
@freeall, please confirm the transfer! Green light from e-conomic

**Comment by freeall** [comment]
Gracias :)

**Pull request merged**
